create database company_abc;
USE COMPANY_ABC;
CREATE TABLE employees (
    emp_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50),
    department VARCHAR(50),
    salary INT,
    city VARCHAR(50),
    joining_year YEAR
);

INSERT INTO employees (name, department, salary, city, joining_year) VALUES
('Amit','HR',30000,'Pune',2020),
('Neha','IT',60000,'Mumbai',2021),
('Rahul','IT',70000,'Delhi',2019),
('Sneha','Finance',50000,'Pune',2022),
('Karan','HR',35000,'Mumbai',2020),
('Priya','IT',65000,'Pune',2021),
('Vikas','Finance',48000,'Delhi',2018),
('Anjali','HR',32000,'Pune',2023),
('Rohit','IT',72000,'Mumbai',2019),
('Pooja','Finance',51000,'Delhi',2022);


SELECT * FROM employees;

SELECT NAME , SALARY 
FROM EMPLOYEES 
WHERE NAME = 'PUNE';

-- Q 1. WRITE ALL COL FROM EMP TABLE WHERE SALARY IS GREATER THAN 50 K

SELECT * FROM EMPLOYEES 
WHERE SALARY > 50000;

-- Q 2. SELECT ALL COLUMNS FROM EMP TABLE WHOSE NAMES STARTS WITH a

SELECT NAME FROM EMPLOYEES
WHERE NAME LIKE 'A%';

-- Q 3.NAME CONTAIN SEC LETER E
SELECT NAME FROM EMPLOYEES
WHERE NAME LIKE '_E%';

-- Q 4. FIRST 3 RECORDS

SELECT * FROM EMPLOYEES
LIMIT 3;

-- Q 5. RETURN UNIQUE CITY FROM EMPLOYEE TABLE

SELECT DISTINCT CITY 
FROM EMPLOYEES ;

-- Q .6 RETURN IT EMPLOYEES WITH HIGH SALARY

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT = 'IT' 
AND SALARY >= 60000;
-- ORDER BY SALARY DESC; 

-- Q 7. RETURN  ALL COL FROM EMPLOYEE SHOWS CITY MUMBAI OR PUEN

SELECT *  FROM EMPLOYEES WHERE 
CITY IN ('MUMBAI','PUNE') ;-- = 'MUMBAI' OR CITY ='PUNE'


-- Q 8. COL WITH SALARY RANGE 40 K TO 70 K

SELECT * FROM EMPLOYEES
WHERE SALARY BETWEEN 40000 AND 70000;

-- Q 9. RETURN ALL COL FROM EMPLOYEE CONTAIN ONLY HR AND FINANCE

SELECT * FROM EMPLOYEES 
WHERE DEPARTMENT = 'FINANCE' OR  DEPARTMENT = 'HR';


-- Q 10 . RETURN  AND ALL COLMS FROM EMPLOYEE SHOW ASC ENDING SALARY

SELECT * FROM EMPLOYEES
ORDER BY SALARY ASC;


-- Q 1A . RETURN  AND ALL COLMS FROM EMPLOYEE SHOW ASCENDING LATEST JOINING
SELECT * FROM EMPLOYEES
ORDER BY JOINING_YEAR DESC;


-- RETURN DEPARTMENT FROM EMPLOYEES TABLE FIND COUNT OF EMPL PER DEPARTMENT
SELECT DEPARTMENT, COUNT(*)
 FROM EMPLOYEES
GROUP BY DEPARTMENT ;


-- Q . FIND AVG SALRY OF EACH DEPARTMENT

SELECT DEPARTMENT, ROUND(AVG(SALARY),2) AS AVG_SALARY 
FROM EMPLOYEES 
GROUP BY  DEPARTMENT;

-- Q . FIND DEPARTMENT WITH MORE THAN 2 EMPLOYEES

SELECT department , COUNT(*) 
FROM EMPLOYEES
GROUP BY department
HAVING COUNT(*) > 2 ;